### ISSUE TITLE
Can't save the ROM

### ISSUE THREAD

**Issue by GoogleCodeExporter** [todtim2/universal-pokemon-randomizer#13]
```
What steps will reproduce the problem?
1. Open the program (command line or by double-clicking)
2. Open the rom (Gold or Silver in my case)
3. Change the options and save.

What is the expected output? What do you see instead?
It should save the randomized ROM, but instead nothing happens...
I'll paste what the shell returns below.

What version of the product are you using? On what operating system?
1.2.0a on Windows 7.

Please provide any additional information below.
When I open the randomizer via shel, here's the result:


F:\Downloads\Randomizer>java -jar randomizer.jar
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Inde
x: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at com.dabomstew.pkrandom.romhandlers.Gen2RomHandler.setStarters(Gen2Rom
Handler.java:816)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.performRandomization(Randomi
zerGUI.java:3130)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROM(RandomizerGUI.java:2
620)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROMButtonActionPerformed
(RandomizerGUI.java:3675)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.access$14(RandomizerGUI.java
:3674)
        at com.dabomstew.pkrandom.gui.RandomizerGUI$15.actionPerformed(Randomize
rGUI.java:1894)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

```

Original issue reported on code.google.com by `benestnut` on 24 Apr 2013 at 12:08

**Comment by GoogleCodeExporter** [comment]
```
Maybe that'll help, but here's the options I picked: (I attached the *rnqs file 
to this comment)

Create a *.rnqs file and put:

x@BBiEApoAnQCXAAQgJAoUFBJQb2tlbW9uIFNpbHZlciAoRincmnFczZevwaaeD2c=

in it. Maybe something in these options makes it glitch, because when I don't 
change anything, it seems to save the ROM just fine... :/

(Remember it's a Gen-2 ROM)
```

Original comment by `benestnut` on 24 Apr 2013 at 12:16

Attachments:
- [Perso.rnqs](https://storage.googleapis.com/google-code-attachments/universal-pokemon-randomizer/issue-13/comment-1/Perso.rnqs)

**Comment by GoogleCodeExporter** [comment]
```
There's something new! The option that made my randomizer not work was touching 
to the starters! Trying to randomize or change them in any way caused the 
randomizer to not save the new ROM!

Hope that helps in any way! ;)
```

Original comment by `benestnut` on 25 Apr 2013 at 3:11

**Comment by GoogleCodeExporter** [comment]
```
Not sure what's causing this yet. When I come back and work on the randomizer 
again, I'll try to find the cause.
```

Original comment by `dabomstew` on 2 May 2013 at 7:24
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Seems to be duplicate with Issue 5 and Issue 29
```

Original comment by `alecro...@gmail.com` on 22 Dec 2013 at 9:55
