### ISSUE TITLE
Randomizer not opening, black coding box flashes.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [todtim2/universal-pokemon-randomizer#37]
```
What steps will reproduce the problem?
1. Opening the randomizer any way
2. ^
3. ^

What is the expected output? What do you see instead?
To open to randomizer. A black coding box flashes.

What version of the product are you using? On what operating system?
1.2.0a (I think,the file just says 120a). Windows 7 (I believe)

Please provide any additional information below.

The coding box says.

Exception in thread "main" java.lang.NoClassDefFoundError: 
D:\Users\tra0001\Desktop\games\Pokemon\Randomizer\randomizer/jar
Caused by: java.lang.ClassNotFoundException: 
D:\Users\tra0001\Desktop\games\Pokemon\Randomizer\randomizer.jar
      at javaj.net.URLClassLoader$1.run(Unknown Source)
      at java.security.AccessController.doProviliged(Native Method)
      at java.net.URLClassLoader.findClass(Unknown Source)
      at java.lang.ClassLoader.loadClass(Unknown Source)
      at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
      at java.lang.ClassLoad.loadClass(Unknown Source)
Could not find the main class: 
D:\Users\tra0001\Desktop\games\Pokemon\Randomizer\raondimzer.jar. Porgram will 
exit.
```

Original issue reported on code.google.com by `calebtra...@gmail.com` on 9 Feb 2014 at 9:48
- Merged into: #21

**Comment by GoogleCodeExporter** [comment]
```
Do things ever get fixed on here?
```

Original comment by `calebtra...@gmail.com` on 20 Feb 2014 at 5:11

**Comment by GoogleCodeExporter** [comment]
```
I'm also getting this issue on my laptop, but it runs fine on my computer.
```

Original comment by `dr...@hotmail.co.uk` on 24 Feb 2014 at 4:03

**Comment by GoogleCodeExporter** [comment]
```
Similar/same issue as #21. Try another PC first, some Java environments are 
incredibly stubborn.
```

Original comment by `dabomstew` on 9 Mar 2014 at 9:04
- Changed state: **Duplicate**
