### ISSUE TITLE
Error trying to save rom

### ISSUE THREAD

**Issue by GoogleCodeExporter** [todtim2/universal-pokemon-randomizer#49]
```
Grabbed me a copy of Blaze Black 2 and tried to run the randomizer

Randomized:

1st starter:machop
make rivals keep starter through whole game regardless of edits
randomized encounters to specific types and no legends
randomized trainers teams by type no legends
swapped statics with similar statics


What version of the product are you using? On what operating system?
1.5 on windows 8.1

Please provide any additional information below.

java.lang.NullPointerException
    at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.randomizeStaticPokemon(AbstractRomHandler.java:958)
    at com.dabomstew.pkrandom.gui.RandomizerGUI.performRandomization(RandomizerGUI.java:3783)
    at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROM(RandomizerGUI.java:3016)
    at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROMButtonActionPerformed(RandomizerGUI.java:4271)
    at com.dabomstew.pkrandom.gui.RandomizerGUI.access$25(RandomizerGUI.java:4270)
    at com.dabomstew.pkrandom.gui.RandomizerGUI$26.actionPerformed(RandomizerGUI.java:2187)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

Is it a problem to try and randomize an already modded game? :/ helps 
appreciated.
```

Original issue reported on code.google.com by `Nicholas...@gmail.com` on 17 Apr 2014 at 4:00

**Comment by GoogleCodeExporter** [comment]
```
Sorry x.x rushed before posting problem lol

Problem: When I try to save my edit It gives the error.txt in my folder hence 
the java error i posted
```

Original comment by `Nicholas...@gmail.com` on 17 Apr 2014 at 4:14

**Comment by GoogleCodeExporter** [comment]
```
ROM hacks such as Blaze Black 2 are not currently supported by the randomizer, 
try randomizing an unmodded game for now.
```

Original comment by `dabomstew` on 14 May 2014 at 4:07
- Changed state: **WontFix**
