### ISSUE TITLE
New Randomized Rom will not appear when click Randomize(Save)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [todtim2/universal-pokemon-randomizer#5]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?
-A new Randomized Rom will appear when i save. Instead when i click 
Randomize(Save), nothing happens at all after i put a new File name and a 
directory to be saved.

What version of the product are you using? On what operating system?
1.2.0, Windows 7 latest Service Pack


Please provide any additional information below.


```

Original issue reported on code.google.com by `Attlebor...@gmail.com` on 22 Feb 2013 at 9:27

**Comment by GoogleCodeExporter** [comment]
```
Please follow these instructions to be able to provide more information on why 
this is going on:

1) Extract the randomizer zip file somewhere.
2) Open up the folder where you extracted it so you can see all the files.
3) Hold the shift button, and right click on somewhere in the window where 
there aren't any files. Choose "Open command window here" from the menu that 
shows up.
4) In the black command prompt window that appears, enter this command exactly 
as it is here:
java -jar randomizer.jar
5) Press enter.
6) The randomizer should open. Use it as normal, try to save, then stop.
7) At this point, right click on the original black command line window, choose 
"Select All", right click again, choose "Copy", and paste what you just copied 
into a reply to this bug to help in solving this problem. 

If you are concerned about posting any private data in that paste (it should 
only show your PC username at the most), you can censor it out before posting 
or email it to me instead (my email is available by clicking on my name on this 
post).

If the randomizer didn't open after you did stage 5), try this command instead:

"C:\Program Files (x86)\Java\jre7\bin\java" -jar randomizer.jar

or if that doesn't work either:


"C:\Program Files (x86)\Java\jre6\bin\java" -jar randomizer.jar
```

Original comment by `dabomstew` on 22 Feb 2013 at 7:12

**Comment by GoogleCodeExporter** [comment]
```

C:\Users\-----\Downloads\UniversalRand>java -jar randomizer.jar 
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Inde
x: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.writeFRLGStarterTex
t(Gen3RomHandler.java:981)
        at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.setStarters(Gen3Rom
Handler.java:922)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.performRandomization(Randomi
zerGUI.java:3145)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROM(RandomizerGUI.java:2
616)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROMButtonActionPerformed
(RandomizerGUI.java:3671)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.access$14(RandomizerGUI.java
:3670)
        at com.dabomstew.pkrandom.gui.RandomizerGUI$15.actionPerformed(Randomize
rGUI.java:1890)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

```

Original comment by `gm.Po0OP` on 23 Feb 2013 at 10:23

**Comment by GoogleCodeExporter** [comment]
```
It works fine when I don't set it to one of the "Random Starter" option.
```

Original comment by `gm.Po0OP` on 23 Feb 2013 at 10:25

**Comment by GoogleCodeExporter** [comment]
```
Will be fixed in next version.
```

Original comment by `dabomstew` on 25 Feb 2013 at 4:54
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Fixed well enough as of 1.2.0a.
```

Original comment by `dabomstew` on 27 Feb 2013 at 2:49
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```

C:\Users\Kai\Desktop\New folder (4)>java -jar randomizer.jar
'java' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Kai\Desktop\New folder (4)>java -jar randomizer.jar
'java' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Kai\Desktop\New folder (4)>"C:\Program Files (x86)\Java\Jre7\bin\java"
-jar randomizer.jar
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 -128185592
        at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.readWildArea(Gen3Ro
mHandler.java:1070)
        at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.getEncounters(Gen3R
omHandler.java:1028)
        at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.randomEncounter
s(AbstractRomHandler.java:350)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.performRandomization(Randomi
zerGUI.java:3264)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROM(RandomizerGUI.java:2
620)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROMButtonActionPerformed
(RandomizerGUI.java:3675)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.access$14(RandomizerGUI.java
:3674)
        at com.dabomstew.pkrandom.gui.RandomizerGUI$15.actionPerformed(Randomize
rGUI.java:1894)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)


```

Original comment by `kaisun...@gmail.com` on 8 Jun 2013 at 5:51

**Comment by GoogleCodeExporter** [comment]
```

C:\Users\Gli Zambrano\Desktop\UPRandomizer-120a>java -jar randomizer.jar
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Inde
x: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.changeStarterWi
thTag(AbstractRomHandler.java:1582)
        at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.rivalCarriesSta
rterUpdate(AbstractRomHandler.java:1509)
        at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.typeThemeTraine
rPokes(AbstractRomHandler.java:766)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.performRandomization(Randomi
zerGUI.java:3205)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROM(RandomizerGUI.java:2
620)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROMButtonActionPerformed
(RandomizerGUI.java:3675)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.access$14(RandomizerGUI.java
:3674)
        at com.dabomstew.pkrandom.gui.RandomizerGUI$15.actionPerformed(Randomize
rGUI.java:1894)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$000(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

```

Original comment by `whitecro...@gmail.com` on 3 Jul 2013 at 12:35

**Comment by GoogleCodeExporter** [comment]
```

C:\Users\the source\Downloads\UPRandomizer-120a>java -randomizer.jar
Unrecognized option: -randomizer.jar
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

C:\Users\the source\Downloads\UPRandomizer-120a>java -jar randomizer.jar
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 61415
        at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.poke3GIndexToNum(Ge
n3RomHandler.java:113)
        at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.removeTradeEvolutio
ns(Gen3RomHandler.java:2098)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.performRandomization(Randomi
zerGUI.java:2935)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROM(RandomizerGUI.java:2
620)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROMButtonActionPerformed
(RandomizerGUI.java:3675)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.access$14(RandomizerGUI.java
:3674)
        at com.dabomstew.pkrandom.gui.RandomizerGUI$15.actionPerformed(Randomize
rGUI.java:1894)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 61415
        at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.poke3GIndexToNum(Ge
n3RomHandler.java:113)
        at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.removeTradeEvolutio
ns(Gen3RomHandler.java:2098)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.performRandomization(Randomi
zerGUI.java:2935)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROM(RandomizerGUI.java:2
620)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROMButtonActionPerformed
(RandomizerGUI.java:3675)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.access$14(RandomizerGUI.java
:3674)
        at com.dabomstew.pkrandom.gui.RandomizerGUI$15.actionPerformed(Randomize
rGUI.java:1894)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 61415
        at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.poke3GIndexToNum(Ge
n3RomHandler.java:113)
        at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.removeTradeEvolutio
ns(Gen3RomHandler.java:2098)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.performRandomization(Randomi
zerGUI.java:2935)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROM(RandomizerGUI.java:2
620)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.saveROMButtonActionPerformed
(RandomizerGUI.java:3675)
        at com.dabomstew.pkrandom.gui.RandomizerGUI.access$14(RandomizerGUI.java
:3674)
        at com.dabomstew.pkrandom.gui.RandomizerGUI$15.actionPerformed(Randomize
rGUI.java:1894)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

```

Original comment by `InFabled...@gmail.com` on 7 Jul 2013 at 4:22

**Comment by GoogleCodeExporter** [comment]
```
The same error happened to me.
With latest version using a Pokemon Cristal French Rom.
The only workaround is to leave starter pokemon unchanged.
Attached the error message.
```

Original comment by `alecro...@gmail.com` on 22 Dec 2013 at 8:29

Attachments:
- [error.log](https://storage.googleapis.com/google-code-attachments/universal-pokemon-randomizer/issue-5/comment-9/error.log)

**Comment by GoogleCodeExporter** [comment]
```

D:\Users\tra0001\Desktop\games\Pokemon\Randomizer>java -jar randomizer.jar
'java' is not recognized as an internal or external command,
operable program or batch file.

D:\Users\tra0001\Desktop\games\Pokemon\Randomizer> -jar randomizer.jar
'-jar' is not recognized as an internal or external command,
operable program or batch file.

D:\Users\tra0001\Desktop\games\Pokemon\Randomizer>randomizer.jar
Exception in thread "main" java.lang.NoClassDefFoundError: D:\Users\tra0001\Desk
top\games\Pokemon\Randomizer\randomizer/jar
Caused by: java.lang.ClassNotFoundException: D:\Users\tra0001\Desktop\games\Poke
mon\Randomizer\randomizer.jar
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: D:\Users\tra0001\Desktop\games\Pokemon\Randomizer
\randomizer.jar.  Program will exit.

D:\Users\tra0001\Desktop\games\Pokemon\Randomizer>
D:\Users\tra0001\Desktop\games\Pokemon\Randomizer>"C:\Progrm Files (x86)\Java\jr
e7\bin\java" -jar randoomizer.jar
The system cannot find the path specified.

D:\Users\tra0001\Desktop\games\Pokemon\Randomizer>"C:\Progrm Files (x86) \Java\j
re7\bin\java" -jar randoomizer.jar
The system cannot find the path specified.

D:\Users\tra0001\Desktop\games\Pokemon\Randomizer>"C:\Progrm Files (x86)\Java\jr
e6\bin\java" -jar randoomizer.jar
The system cannot find the path specified.

That's my log, tried everything and nothing work.
```

Original comment by `calebtra...@gmail.com` on 9 Feb 2014 at 9:33
